title: CLI Schema
description: The open standard for describing command-line interfaces
baseurl: "/cli-schema"
url: "https://cli-schema.github.io"

theme: minima

minima:
  skin: classic

header_pages:
  - why.md
  - spec.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge

kramdown:
  syntax_highlighter: rouge

defaults:
  - scope:
      path: ""
    values:
      layout: default
